### ISSUE TITLE
Removed command line option `-l` is used

### ISSUE THREAD

**Issue by malex984** [IMAGINARY/kiosk-browser#38]
`-l` command line option is used (at least at Supernova) and by `hb_preload.sh` due to adding additional command line options at the end of command line...

**Comment by porst17** [comment]
If you want to upgrade to recent kiosk browser versions, you can refactor your wrapper scripts to add CLI options at the beginning instead of the end of the command line, so positional arguments at the end (like URLs) still work.

**Comment by malex984** [comment]
Ok. Just note that A LOT of refactoring will be necesasary if we decide to use/test this new kiosk-browser at Supernova.
